### PR TITLE
KillSwitch (SnakeGameEnd.bat)

### PR DESCRIPTION
**Pull request by TheCorsairMan**
Kill Switch which can be bound to any key and closes KeyboardMinigames without using task manager or cmd(manually)

### CODE REVIEW

**Comment by MythicManiac** [comment]
Just hitting ESC already does this, although I don't think this is a bad idea. Adding instructions how to use this to the readme would be appreciated, however.

**Comment by TheCorsairMan** [comment]
Bind the program the same as SnakeGame.bat

Use CUE's "Assign new action" --> Shortcut --> Run the following --> SnakeGameEnd.bat

So if you had PGUP binded to SnakeGame.bat then you could have PGDOWN binded as SnakeGameEnd.bat.

**Comment by MythicManiac** [comment]
What I meant was also committing a modified Readme with this PR, so I don't have to modify it later. I'll merge this once that's done, or if I get around modifying it myself.

**Comment by TheCorsairMan** [comment]
Closing pull request.

**Pull request closed without merging**
