### PR TITLE
Add K95 support

### PR DESCRIPTION
**Pull request by gweedo767**
Look for either a K70 or K95

### CODE REVIEW

**Comment by MythicManiac** [comment]
This is great :+1:

**Comment by andi1up** [comment]
Hella late for this but the K95 Platinum isn't working at all with this.

**Comment by MythicManiac** [comment]
@andi1up you could try using a newer version of the `CUE.NET` (https://github.com/DarthAffe/CUE.NET) library and see if it does anything. Personally I can't test it since I don't own said keyboard, but my best guess would be that it uses some newer interface that the version of `CUE.NET` we're using doesn't support. Ours is over a year old aferall

**Comment by andi1up** [comment]
@MythicManiac Not sure if I'm just a complete dunce but I placed the new `CUE.NET ` where the previous files were, still to no luck. I understand you don't have the keyboard and all, but got do you have any other idea?

Edit: I downloaded the masters and replaced the `CUE.NET ` files in there and it turns out CorsairKeyboardKeyID doesn't exist. It's replaced with CorsairKeyboardLedID, but theres still an error if you wouldn't mind checking it out.

**Comment by MythicManiac** [comment]
I don't have access to any windows workstation before next weekend, but if you can describe the error(s) here I might be able to tell what to do.

**Comment by andi1up** [comment]
In this block under KeyboardInterface.cs
```
        public void SetLed(int index, int r, int g, int b)
        {
            SetLed((CorsairKeyboardKeyId)index, r, g, b);
        }
```

I get the error 

> Error	CS0246	The type or namespace name 'CorsairKeyboardKeyId' could not be found (are you missing a using directive or an assembly reference?)

Same applies to this one. 
```
        public void SetLed(CorsairKeyboardKeyId keyId, int r, int g, int b)
        {
            var key = Keyboard[keyId];
            if (key == null) { return; }
            key.Led.Color = Color.FromArgb(r, g, b);
        }
```

So I replaced `CorsairKeyboardKeyId ` with what it seemed to be replaced with, `CorsairKeyboardLedId `.
 The error I get for the first one is 

>Error	CS0716	Cannot convert to static type 'CorsairKeyboardLedId'

Along with 

> Error	CS1503	Argument 1: cannot convert from 'CUE.NET.Devices.Keyboard.Enums.CorsairKeyboardLedId' to 'char'

And `var key = Keyboard[keyId]; ` gives off an error stating...
> Error	CS0721	'CorsairKeyboardLedId': static types cannot be used as parameters

Not sure if that can give any details, but it's all I got.

Edit: Looks like by replacing `CorsairKeyboardLedId ` with `CorsairLedId ` solved some errors. Leaving with 1 error, stating 
> Error CS1061   'CorsairLed' does not contain a definition for 'Led' and no extension method 'Led' accepting a first argument of type 'CorsairLed' could be found (are you missing a using directive or an assembly reference?)

**Comment by MythicManiac** [comment]
The commit which removed the functionality we were relying on seems to be https://github.com/DarthAffe/CUE.NET/commit/223c0e88864d35fb5bdc30f5399e33170f53f2ad
and it seems the `CorsairLedId` class is actually what we want to use, as seen here:
https://github.com/DarthAffe/CUE.NET/blob/master/Devices/Generic/Enums/CorsairLedId.cs
https://github.com/DarthAffe/CUE.NET/blob/master/Devices/Generic/AbstractCueDevice.cs#L75
so what we want to do is somehow convert our `keyId` to the `CorsairLedId` format

Doing the following could work:
```C#
        public void SetLed(int index, int r, int g, int b)
        {
            SetLed((CorsairLedId)index, r, g, b);
        }
```
and
```C#
        public void SetLed(CorsairLedId keyId, int r, int g, int b)
        {
            var key = Keyboard[keyId];
            if (key == null) { return; }
            key.Led.Color = Color.FromArgb(r, g, b);
        }
```
Good luck 👍

**Comment by andi1up** [comment]
~~Alright, I wrote that but `key.Led.Color ` gives off an error to `Led `~~
~~>Error	CS1061	'CorsairLed' does not contain a definition for 'Led' and no extension method 'Led'~~ ~~accepting a first argument of type 'CorsairLed' could be found (are you missing a using directive or an~~ ~~assembly reference?)~~	 

~~Getting rid of `Led ` and having just `key.Color ` seems to get rid of the error, but nothing happens on~~ ~~the keyboard, so I don't think that's the solution.~~

I'm an idiot, I was running from Visual Studios the entire time. To anyone else browsing this, simply update CUE.NET and change anything that says `CorsairKeyboardKeyId `  to `CorsairLedId `.

Also change `key.Led.Color ` to `key.Color `.

@MythicManiac Thanks a bunch!

**Comment by MythicManiac** [comment]
@andi1up No problem! If you'd be kind enough to submit a PR with the changes you made, it would be much appreciated 👌

**Comment by andi1up** [comment]
@MythicManiac I added a PR, I don't really submit PR so I'm not sure how hard I messed up doing it.

**Pull request merged**
